-- Seed: Vorerfassungsliste aus Schulnetz-Lehrpersonenplan SJ 2025/2026
-- 198 Lehrpersonen mit Fachbereich und Beruf

INSERT INTO lehrperson_vorerfassung (vorname, nachname, fachbereich, beruf)
VALUES
  ('Julia', 'Abächerli', 'Sport', ''),
  ('Tobias', 'Acklin', 'Berufskunde', 'Informatiker/in Plattformentwicklung EFZ'),
  ('Sandra', 'Affentranger', 'Berufskunde', 'Fachfrau/Fachmann Hotellerie-Hauswirtschaft EFZ'),
  ('Sira', 'Alder', 'Berufskunde', 'Automobil-Fachmann/-frau EFZ'),
  ('Raphael', 'Alt', 'Berufskunde', 'Koch/Köchin EFZ'),
  ('Simon', 'Althaus', 'Berufskunde', 'Automobil-Mechatroniker/in EFZ'),
  ('Hans', 'Amberg', 'Berufskunde', ''),
  ('Bernadette', 'Ammann', 'Allgemeinbildung', ''),
  ('Niklaus', 'Anklin', 'Berufsmatura', ''),
  ('Sonja', 'Appert', 'Berufsmatura', ''),
  ('Jessica', 'Aregger', 'Berufskunde', ''),
  ('Myriam', 'Arnelas', 'Berufskunde', 'Zeichner/in EFZ Fachrichtung Architektur'),
  ('Markus', 'Attinger', 'Sport', ''),
  ('Philippe', 'Babey', 'Berufsmatura', ''),
  ('Mathias', 'Bachmann', 'Berufskunde', ''),
  ('Pascal', 'Bammert', 'Berufskunde', 'Informatiker/in Applikationsentwicklung EFZ'),
  ('Michael', 'Barry', 'Berufskunde', 'Informatiker/in Applikationsentwicklung EFZ'),
  ('Ueli', 'Baumann', 'Berufskunde', 'Elektroniker/in EFZ'),
  ('Ulrich', 'Baur', 'Berufsmatura', ''),
  ('Elia', 'Becci', 'Berufskunde', 'Automobil-Fachmann/-frau EFZ'),
  ('Valentin', 'Beduhn', 'Englisch', ''),
  ('Geena', 'Benga', 'Berufskunde', ''),
  ('Reto', 'Benz', 'Berufskunde', ''),
  ('Markus', 'Betschart', 'Berufskunde', ''),
  ('Marc', 'Bettschen', 'Berufskunde', ''),
  ('Chiara', 'Bieler', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Carina', 'Bieri', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Silvan', 'Bieri', 'Berufskunde', ''),
  ('Margrit', 'Bolliger', 'Berufsmatura', ''),
  ('Linda', 'Borsai', 'Berufskunde', ''),
  ('Andreas', 'Bossard', 'Mathematik', ''),
  ('David', 'Bradley', 'Berufskunde', 'Fachfrau/Fachmann Gesundheit EFZ'),
  ('Miriam', 'Braun', 'Berufsmatura', ''),
  ('Stefan', 'Brehm', 'Berufskunde', ''),
  ('Sibylle', 'Bucher', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Carmen', 'Buder', 'Allgemeinbildung', ''),
  ('Timon', 'Burkard', 'Berufskunde', 'Höhere Fachschule Informatik'),
  ('Adriano', 'Carminitana', 'Berufskunde', 'Sanitärinstallateur/in EFZ'),
  ('Patrick', 'Carulli', 'Berufskunde', 'Polymechaniker/in EFZ'),
  ('Nathalie', 'Casillo', 'Berufskunde', 'Fachfrau/Fachmann Gesundheit EFZ'),
  ('Raul', 'Costa', 'Berufskunde', ''),
  ('Giuseppe', 'Cucuzza', 'Berufskunde', ''),
  ('Christian', 'Deuber', 'Berufskunde', ''),
  ('Geraldine', 'Dietrich', 'Allgemeinbildung', ''),
  ('Bettina', 'Dober', 'Berufskunde', 'Informatiker/in Applikationsentwicklung EFZ'),
  ('Christoph', 'Eggenspieler', 'Berufskunde', ''),
  ('Susanne', 'Eglauf', 'Berufskunde', ''),
  ('Daniel', 'Eichmüller', 'Berufskunde', 'Automobil-Mechatroniker/in EFZ'),
  ('Antonia', 'Erni', 'Berufskunde', 'Fachfrau/Fachmann Gesundheit EFZ'),
  ('Fabienne', 'Erzinger', 'Berufskunde', ''),
  ('Matthias', 'Essig', 'Berufskunde', 'Automobil-Fachmann/-frau EFZ'),
  ('Janine', 'Ezer', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Reto', 'Fessler', 'Berufsmatura', ''),
  ('Tobias', 'Feusi', 'Berufskunde', ''),
  ('Remo', 'Flury', 'Berufskunde', ''),
  ('Roli', 'Frei', 'Sport', ''),
  ('Estefania', 'Frei-Otero', 'Englisch', ''),
  ('Christian', 'Freimann', 'Berufskunde', 'Montage-Elektriker/in EFZ'),
  ('Antoinette', 'Freivogel', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Nora', 'Frey', 'Sport', ''),
  ('Paul M.', 'Furrer', 'Berufskunde', 'Elektroinstallateur/in EFZ'),
  ('Tanja', 'Furrer', 'Berufskunde', ''),
  ('Elio', 'Gallo', 'Berufskunde', 'Elektroinstallateur/in EFZ'),
  ('Beate', 'Gau', 'Berufsmatura', ''),
  ('Kevin', 'Gehrig', 'Sport', ''),
  ('Peter', 'Gisler', 'Berufskunde', 'Informatiker/in Applikationsentwicklung EFZ'),
  ('Dominik', 'Gmür', 'Berufsmatura', ''),
  ('Christoph', 'Goechnahts', 'Berufskunde', ''),
  ('Florian', 'Graf', 'Berufskunde', ''),
  ('Reto', 'Grepper', 'Berufskunde', 'Zeichner/in EFZ Fachrichtung Ingenieurbau'),
  ('Martin', 'Greutmann', 'Berufskunde', ''),
  ('Markus', 'Gut', 'Berufsmatura', ''),
  ('Jean-Luc', 'Haas', 'Berufskunde', 'Informatiker/in Applikationsentwicklung EFZ'),
  ('Alexandra', 'Haas-Bauer', 'Berufskunde', ''),
  ('Roman', 'Hatz', 'Englisch', ''),
  ('Anke', 'Hauenschild', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Simon', 'Haueter', 'Sport', ''),
  ('Regula', 'Hauser', 'Berufskunde', ''),
  ('Thomas', 'Hausheer', 'Berufskunde', 'Informatiker/in Plattformentwicklung EFZ'),
  ('Claudia', 'Hegglin', 'Allgemeinbildung', ''),
  ('Christian', 'Hegglin', 'Sport', ''),
  ('Daniela', 'Hegglin', 'Berufskunde', ''),
  ('Urs', 'Hegglin', 'Berufskunde', ''),
  ('Peter', 'Hegi', 'Berufskunde', 'Zeichner/in EFZ Fachrichtung Architektur'),
  ('Martin', 'Hegner', 'Sport', ''),
  ('Christoph', 'Heimburger', 'Berufskunde', 'Konstrukteur/in EFZ'),
  ('Daniel', 'Henggeler', 'Berufskunde', 'Elektroinstallateur/in EFZ'),
  ('Patricia', 'Heraty', 'Berufsmatura', ''),
  ('Philipp', 'Herzog', 'Berufskunde', 'Elektroniker/in EFZ'),
  ('Markus', 'Hostettler', 'Berufskunde', 'Höhere Fachschule Gebäudetechnik'),
  ('Daniel', 'Huber', 'Berufskunde', ''),
  ('Claudio', 'Hübscher', 'Berufskunde', ''),
  ('Franz', 'Hürlimann', 'Berufskunde', ''),
  ('Tanja', 'Imgrüth', 'Berufskunde', 'Coiffeur/-euse EFZ'),
  ('Ramona', 'Isler', 'Berufskunde', 'Fachfrau/Fachmann Gesundheit EFZ'),
  ('Annette', 'Iten', 'Englisch', ''),
  ('Tabea', 'Jung', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Saira', 'Kaufmann', 'Berufskunde', ''),
  ('Heinz', 'Klein', 'Berufskunde', ''),
  ('Ernst', 'Kleiner', 'Berufskunde', 'Konstrukteur/in EFZ'),
  ('Pascale', 'Köppel', 'Berufsmatura', ''),
  ('Jürg', 'Körner', 'Sport', ''),
  ('Carla', 'Kronig', 'Berufskunde', ''),
  ('Conny', 'Kuhles', 'Allgemeinbildung', ''),
  ('Beat', 'Kündig', 'Allgemeinbildung', ''),
  ('Benjamin', 'Landolt', 'Berufsmatura', ''),
  ('Christian', 'Lindauer', 'Berufskunde', 'Informatiker/in Applikationsentwicklung EFZ'),
  ('Elena', 'Lorenzo', 'Berufskunde', ''),
  ('Sabrina', 'Lötscher', 'Berufskunde', ''),
  ('Caroline', 'Lüscher', 'Berufskunde', 'Fachfrau/Fachmann Gesundheit EFZ'),
  ('Monika', 'Makart', 'Berufskunde', 'Fachfrau/Fachmann Hotellerie-Hauswirtschaft EFZ'),
  ('Thomas', 'Marbacher', 'Berufskunde', 'Zahntechniker/in EFZ'),
  ('Karl', 'Marbet', 'Berufskunde', ''),
  ('Manuela', 'Marty', 'Berufskunde', 'Fachfrau/Fachmann Gesundheit EFZ'),
  ('Arthur', 'Mathis', 'Sport', ''),
  ('Marco', 'Mehr', 'Berufskunde', 'Koch/Köchin EFZ'),
  ('Michael', 'Mettler', 'Berufskunde', 'Automobil-Fachmann/-frau EFZ'),
  ('Laura', 'Moell', 'Berufskunde', 'Fachfrau/Fachmann Gesundheit EFZ'),
  ('Claudio', 'Moos', 'Berufskunde', 'Maurer/in EFZ'),
  ('Aaron', 'Moser', 'Berufskunde', 'Elektroinstallateur/in EFZ'),
  ('Roger', 'Muggli', 'Sport', ''),
  ('Loris', 'Müller', 'Berufskunde', 'Fachfrau/Fachmann Gesundheit EFZ'),
  ('Roger', 'Müller', 'Berufskunde', 'ICT-Fachmann/-frau EFZ'),
  ('Jürg', 'Neidhart', 'Berufsmatura', ''),
  ('Simon', 'Neidhart', 'Berufskunde', ''),
  ('Markus', 'Nussbaumer', 'Berufskunde', 'Informatiker/in Plattformentwicklung EFZ'),
  ('Thomas', 'Oberlin', 'Berufskunde', ''),
  ('Maria', 'Odermatt', 'Berufskunde', ''),
  ('Bernhard', 'Parodi', 'Berufsmatura', ''),
  ('Chiara', 'Parodi', 'Englisch', ''),
  ('Giancarlo', 'Pascarella', 'Berufskunde', ''),
  ('Raabe', 'Pauli', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Reg. Regula', 'Pauli', 'Berufskunde', 'Fachfrau/Fachmann Gesundheit EFZ'),
  ('Markus', 'Perchtaler', 'Berufskunde', 'Zahntechniker/in EFZ'),
  ('Fabio', 'Petranca', 'Berufskunde', 'Reifenpraktiker/in EBA'),
  ('Tobias', 'Pulfer', 'Berufskunde', 'Informatiker/in Applikationsentwicklung EFZ'),
  ('Matthias', 'Püntener', 'Berufskunde', ''),
  ('Rajmonda', 'Quni', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Silvan', 'Renggli', 'Berufskunde', ''),
  ('Stefan', 'Rickli', 'Berufskunde', ''),
  ('Cèdric', 'Rihs', 'Sport', ''),
  ('Roger', 'Rogenmoser', 'Berufskunde', ''),
  ('Yasmin', 'Rohrer', 'Berufskunde', ''),
  ('Manuel', 'Rohrer', 'Berufskunde', 'Elektroinstallateur/in EFZ'),
  ('Lorenz', 'Roos', 'Berufskunde', 'Elektroniker/in EFZ'),
  ('Sabrina', 'Rüegg', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Szabolcs', 'Sajo', 'Berufskunde', 'Automobil-Fachmann/-frau EFZ'),
  ('Marcus', 'Schawalder', 'Berufskunde', 'Maurer/in EFZ'),
  ('Daniel', 'Scherrer', 'Berufsmatura', ''),
  ('Simon', 'Schibig', 'Berufskunde', ''),
  ('Robert', 'Schlittler', 'Englisch', ''),
  ('Silvio', 'Schlumpf', 'Sport', ''),
  ('René', 'Schmid', 'Berufskunde', ''),
  ('Tobias', 'Schmid', 'Berufskunde', 'Höhere Fachschule Informatik'),
  ('Willi', 'Schmidt', 'Allgemeinbildung', ''),
  ('Edith', 'Schöb', 'Allgemeinbildung', ''),
  ('Astrid', 'Schönenberger', 'Berufskunde', ''),
  ('Peter', 'Schork', 'Berufskunde', 'Zahntechniker/in EFZ'),
  ('Edith', 'Schurtenberger', 'Berufskunde', ''),
  ('Noëlla', 'Schüttel', 'Berufsmatura', ''),
  ('Markus', 'Schwindl', 'Berufsmatura', ''),
  ('Manuela', 'Speck', 'Berufsmatura', ''),
  ('Niklaus', 'Stadelmann', 'Berufskunde', ''),
  ('Philipp', 'Stalder', 'Berufskunde', ''),
  ('Dave', 'Stamm', 'Berufsmatura', ''),
  ('Corina', 'Steffen', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Michele', 'Stranieri', 'Berufskunde', 'Automobil-Fachmann/-frau EFZ'),
  ('Robert', 'Theiler', 'Berufskunde', 'Automobil-Fachmann/-frau EFZ'),
  ('Andreja', 'Torriani', 'Berufskunde', 'Elektroinstallateur/in EFZ'),
  ('Guido', 'Trachsler', 'Allgemeinbildung', ''),
  ('Markus', 'Trinkler', 'Sport', ''),
  ('David', 'Trost', 'Berufskunde', 'Automatiker/in EFZ'),
  ('Ermira', 'Tuzi', 'Berufsmatura', ''),
  ('Denis', 'Vejnovic', 'Berufsmatura', ''),
  ('Goran', 'Vejnovic', 'Mathematik', ''),
  ('Michael', 'Vollenweider', 'Sport', ''),
  ('Miriam', 'Vollmer', 'Berufskunde', 'Fachfrau/Fachmann Betreuung EFZ'),
  ('Beat', 'von Holzen', 'Berufskunde', ''),
  ('Irène', 'Waldispühl', 'Berufskunde', ''),
  ('Gabriel', 'Weber', 'Berufskunde', ''),
  ('Raphael', 'Weiss', 'Berufsmatura', ''),
  ('Sonja', 'Werne', 'Berufskunde', 'Zahntechniker/in EFZ'),
  ('Manuela', 'Wey', 'Berufskunde', ''),
  ('Roger', 'Wiedermeier', 'Berufsmatura', ''),
  ('Christoph', 'Wildhaber', 'Berufskunde', 'Automobil-Mechatroniker/in EFZ'),
  ('Andrea', 'Winkler', 'Berufskunde', 'Coiffeur/-euse EFZ'),
  ('Lukas', 'Winter', 'Sport', ''),
  ('Reto', 'Wirz', 'Berufskunde', 'Elektroinstallateur/in EFZ'),
  ('Peter', 'Wlodarczak', 'Berufskunde', ''),
  ('Marcel', 'Würsch', 'Berufskunde', ''),
  ('Özkan', 'Yapici', 'Berufskunde', ''),
  ('Armin', 'Zaugg', 'Englisch', ''),
  ('Beat', 'Zgraggen', 'Berufskunde', 'Schreiner/in EFZ'),
  ('Katja', 'Zgraggen', 'Berufsmatura', ''),
  ('Marco', 'Zimmermann', 'Berufsmatura', ''),
  ('Sandra', 'Zurbuchen', 'Berufskunde', 'Fachfrau/Fachmann Hotellerie-Hauswirtschaft EFZ'),
  ('Mark', 'Zurfluh', 'Berufsmatura', ''),
  ('Mathias', 'Ulrich', 'Mathematik', '')
ON CONFLICT DO NOTHING;
